name: flutter_project
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.0-122.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.8
  flutter_native_splash: ^2.3.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  get_it: ^7.6.4
  shared_preferences: ^2.2.2
  dio: ^5.3.3
  flutter_bloc: ^8.1.3


flutter_native_splash:
  color: "#1463F5"
  ios: false

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: RalewayRegular
      fonts:
        - asset: fonts/Raleway-Regular.ttf
          weight: 400
    - family: RalewaySemiBold
      fonts:
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600
